"""Korean EV Automotive Slang, Profanity, and Defect Lexicon.

Contains 70+ authentic community terms across 6 core dimensions:
1. Brand Pejorative (맹목적 팬덤 및 제조사 비하)
2. Sound / Noise / Vibration (모터, 인버터, 하부 소음)
3. Build Quality & Cabin (단차, 누수, 마감 불량)
4. Battery, Charging & Thermal (ICCU 폭탄, 12V 방전, 충전 오류)
5. Driving Dynamics & ADAS (피쉬테일, 팬텀 브레이킹, 페달 먹통)
6. Service, Repair & Economics (전손폭탄, 통교체 갑질, 하드웨어 인질극)

Authoritative reference:
/Users/a7890/src/my-e-car/.agents/spec_miner_nlp_workflow/specifications.md § 2.1
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


@dataclass(frozen=True)
class SlangEntry:
    term: str
    dimension: str  # BRAND_PEJORATIVE, SOUND_NOISE, BUILD_QUALITY, BATTERY_CHARGING, DRIVING_DYNAMICS, SERVICE_ECONOMICS
    defect_category: Optional[str]  # BATTERY_CHARGING, DRIVING_POWERTRAIN, BUILD_QUALITY, SOFTWARE_ELECTRONICS, SERVICE_REPAIR_COST
    meaning: str
    severity_weight: int  # 1 to 5
    default_polarity: float  # -1.0 to +1.0
    safety_impact: float = 0.0
    functional_impact: float = 0.0
    economic_impact: float = 0.0
    social_impact: float = 0.0
    convenience_impact: float = 0.0
    example: str = ""


# Exhaustive Catalog of 70+ Korean EV Automotive Community Terms
RAW_SLANG_ENTRIES: List[SlangEntry] = [
    # -------------------------------------------------------------
    # 1. BRAND PEJORATIVES (6 terms)
    # -------------------------------------------------------------
    SlangEntry(
        term="테슬람",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="테슬라의 결함조차 무비판적으로 찬양하는 극성 팬덤 비하",
        severity_weight=2,
        default_polarity=-0.65,
        social_impact=5.0,
        example="단차로 비 새는데도 테슬람들은 감성이라고 빨아주네 ㅋㅋㅋ",
    ),
    SlangEntry(
        term="현기충",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="현대/기아차를 맹목적으로 옹호하는 유저 비하",
        severity_weight=2,
        default_polarity=-0.60,
        social_impact=5.0,
        example="ICCU로 고속도로에서 멈춰봐야 현기충 탈출하지.",
    ),
    SlangEntry(
        term="흉기차",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="현대기아의 안전 결함(급발진, 에어백 미전개)을 비판하는 멸칭",
        severity_weight=4,
        default_polarity=-0.80,
        safety_impact=4.0,
        social_impact=7.0,
        example="흉기차 타다 급발진 나면 평생 블핸에서 과실치사 당한다.",
    ),
    SlangEntry(
        term="흉기",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="현대기아차 약칭 멸칭",
        severity_weight=3,
        default_polarity=-0.75,
        social_impact=6.5,
        example="흉기 전기차는 고속도로 1차로 시한폭탄임.",
    ),
    SlangEntry(
        term="개슬라",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="악명 높은 테슬라 AS 지연, 가격 인하에 대한 분노 표현",
        severity_weight=3,
        default_polarity=-0.70,
        social_impact=6.0,
        example="개슬라 AS 예약 잡으려다 석 달 뒤로 밀려서 암 걸릴 뻔.",
    ),
    SlangEntry(
        term="개스라",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="개슬라의 발음 표기 변형",
        severity_weight=3,
        default_polarity=-0.70,
        social_impact=6.0,
        example="개스라 서비스센터는 갈 때마다 싸우고 나옴.",
    ),
    SlangEntry(
        term="짱깨차",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="BYD 등 중국산 전기차를 비하하는 극단적 멸칭",
        severity_weight=4,
        default_polarity=-0.85,
        social_impact=8.0,
        example="그 돈 주고 짱깨차 사서 지하주차장 눈치 보며 사냐?",
    ),
    SlangEntry(
        term="짱차",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="중국산 전기차 비하 약칭",
        severity_weight=4,
        default_polarity=-0.80,
        social_impact=7.5,
        example="짱차 지하주차장 못 들어오게 막아야 한다.",
    ),
    SlangEntry(
        term="서민포르쉐",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="테슬라 모델3/아이오닉5를 조롱하는 비꼬는 별칭",
        severity_weight=2,
        default_polarity=-0.50,
        social_impact=4.0,
        example="서민포르쉐 타고 쏘더니 방지턱 넘고 하부 긁힘 ㅋㅋㅋ",
    ),
    SlangEntry(
        term="퐁퐁차",
        dimension="BRAND_PEJORATIVE",
        defect_category=None,
        meaning="패밀리 EV를 비하하거나 가성비 구매를 조롱하는 표현",
        severity_weight=2,
        default_polarity=-0.55,
        social_impact=4.5,
        example="가족용 퐁퐁차 샀다가 충전 스트레스만 왕창 받음.",
    ),

    # -------------------------------------------------------------
    # 2. SOUND / NOISE / VIBRATION (8 terms)
    # -------------------------------------------------------------
    SlangEntry(
        term="밥솥",
        dimension="SOUND_NOISE",
        defect_category="DRIVING_POWERTRAIN",
        meaning="전기차 감속기/인버터/조향모터의 고주파 이음이 밥솥 취사음 같음",
        severity_weight=3,
        default_polarity=-0.70,
        functional_impact=5.0,
        convenience_impact=8.5,
        example="엑셀 밟을 때마다 모터에서 밥솥 취사소리 삐익 나는데 센터선 정상이래.",
    ),
    SlangEntry(
        term="밥솥소리",
        dimension="SOUND_NOISE",
        defect_category="DRIVING_POWERTRAIN",
        meaning="감속기 및 인버터 고주파 노이즈",
        severity_weight=3,
        default_polarity=-0.70,
        functional_impact=5.5,
        convenience_impact=8.5,
        example="가속 페달 밟으면 밥솥소리 너무 심해서 귀가 아픔.",
    ),
    SlangEntry(
        term="찌걱찌걱",
        dimension="SOUND_NOISE",
        defect_category="BUILD_QUALITY",
        meaning="어퍼암 부싱, 스테빌라이저 링크 마찰로 인한 하부 잡소리",
        severity_weight=3,
        default_polarity=-0.65,
        functional_impact=4.0,
        convenience_impact=8.0,
        example="방지턱 넘을 때마다 하부에서 찌걱찌걱 귀신 우는 소리 난다.",
    ),
    SlangEntry(
        term="잡소리",
        dimension="SOUND_NOISE",
        defect_category="BUILD_QUALITY",
        meaning="내장재 플라스틱 마찰음 및 글라스루프 이음",
        severity_weight=3,
        default_polarity=-0.60,
        convenience_impact=7.5,
        example="신차 출고한 지 한 달도 안 됐는데 대시보드 잡소리 미쳤네.",
    ),
    SlangEntry(
        term="귀신소리",
        dimension="SOUND_NOISE",
        defect_category="BUILD_QUALITY",
        meaning="풍절음 또는 하부 부싱에서 나는 기괴한 바람소리/마찰음",
        severity_weight=3,
        default_polarity=-0.70,
        convenience_impact=8.0,
        example="고속도로만 올리면 A필러에서 귀신소리 휘파람 불어서 미치겠음.",
    ),
    SlangEntry(
        term="풍절음",
        dimension="SOUND_NOISE",
        defect_category="BUILD_QUALITY",
        meaning="창문 프레임리스 글라스 또는 도어 고무 몰딩 틈새 바람소리",
        severity_weight=2,
        default_polarity=-0.55,
        convenience_impact=7.0,
        example="80km 넘어가면 풍절음 때문에 동승자랑 대화가 안 됨.",
    ),
    SlangEntry(
        term="고주파음",
        dimension="SOUND_NOISE",
        defect_category="DRIVING_POWERTRAIN",
        meaning="인버터/모터 스위칭 노이즈로 인한 이명 유발 소음",
        severity_weight=3,
        default_polarity=-0.65,
        convenience_impact=8.5,
        example="실내 정숙성은 좋은데 감속할 때 모터 고주파음이 뇌를 찌름.",
    ),
    SlangEntry(
        term="모터이음",
        dimension="SOUND_NOISE",
        defect_category="DRIVING_POWERTRAIN",
        meaning="구동 모터 베어링 및 감속기 기어 유격 소음",
        severity_weight=3,
        default_polarity=-0.70,
        functional_impact=6.5,
        convenience_impact=7.0,
        example="모터이음 문제로 사업소 들어갔더니 통교체 대기만 2달이라네요.",
    ),

    # -------------------------------------------------------------
    # 3. BUILD QUALITY & CABIN (10 terms)
    # -------------------------------------------------------------
    SlangEntry(
        term="단차",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="도어, 보닛, 트렁크 등 외장 패널 간격 불일치",
        severity_weight=3,
        default_polarity=-0.65,
        convenience_impact=8.0,
        example="트렁크 좌우 단차에 손가락 들어가는데 이게 7천만원짜리 차냐?",
    ),
    SlangEntry(
        term="단차지옥",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="외장 패널 전반이 뒤틀려 조립 불량이 극심한 상태",
        severity_weight=4,
        default_polarity=-0.80,
        convenience_impact=9.0,
        example="신차 검수 갔다가 단차지옥 보고 바로 인수거부 때림.",
    ),
    SlangEntry(
        term="단차뽑기",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="조립 품질 편차가 심해 양품 인수가 가챠 게임 같음",
        severity_weight=3,
        default_polarity=-0.65,
        convenience_impact=7.5,
        example="이번 하이랜드 단차뽑기 망해서 도어랑 휀더 라인 다 틀어짐.",
    ),
    SlangEntry(
        term="누수",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="웨더스트립 불량으로 빗물 또는 세차수가 실내/트렁크로 유입",
        severity_weight=4,
        default_polarity=-0.85,
        safety_impact=4.0,
        functional_impact=6.0,
        convenience_impact=9.0,
        example="세차하고 트렁크 열었더니 바닥에 누수돼서 물이 흥건함.",
    ),
    SlangEntry(
        term="워터파크",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="실내 바닥이나 트렁크에 물이 고여 수영장처럼 된 심각한 누수",
        severity_weight=5,
        default_polarity=-0.90,
        safety_impact=5.0,
        functional_impact=7.0,
        convenience_impact=9.5,
        example="세차 한번 돌렸더니 서브트렁크 바닥에 물 차서 워터파크 개장함.",
    ),
    SlangEntry(
        term="웨더스트립",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="도어/유리 실링 고무 몰딩 이탈 및 찢어짐",
        severity_weight=3,
        default_polarity=-0.60,
        convenience_impact=7.0,
        example="출고 3일 만에 도어 웨더스트립이 빠져서 덜렁거림.",
    ),
    SlangEntry(
        term="도어캐치 실종",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="플러시 타입 전자 도어 핸들이 팝업되지 않거나 안으로 꺼짐",
        severity_weight=4,
        default_polarity=-0.80,
        functional_impact=7.0,
        convenience_impact=8.5,
        example="추운 아침에 도어캐치 실종돼서 차 문을 못 열고 출근 포기함.",
    ),
    SlangEntry(
        term="동결 고착",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="혹한기 플러시 도어 핸들 또는 충전구 덮개가 얼어붙어 작동 불가",
        severity_weight=4,
        default_polarity=-0.75,
        functional_impact=6.5,
        convenience_impact=8.5,
        example="충전구 도어가 동결 고착돼서 완속 충전기도 못 꽂음.",
    ),
    SlangEntry(
        term="도장 불량",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="외장 페인트 뭉침, 칠 까짐, 오렌지필 결함",
        severity_weight=3,
        default_polarity=-0.65,
        convenience_impact=7.5,
        example="휀더 도장 불량으로 클리어층 벗겨진 거 보고 빡침.",
    ),
    SlangEntry(
        term="마감 불량",
        dimension="BUILD_QUALITY",
        defect_category="BUILD_QUALITY",
        meaning="내외장 조립 마감 허술 및 단차",
        severity_weight=3,
        default_polarity=-0.65,
        convenience_impact=7.5,
        example="플라스틱 트림 마감 불량이라 손가락 베일 뻔함.",
    ),

    # -------------------------------------------------------------
    # 4. BATTERY, CHARGING & THERMAL (16 terms)
    # -------------------------------------------------------------
    SlangEntry(
        term="ICCU 폭탄",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="현대 E-GMP 통합 충전 제어 장치 파워모듈 소손으로 인한 주행 중 멈춤",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        functional_impact=9.5,
        economic_impact=8.0,
        example="주행 중 펑 소리 나더니 전원공급장치 점검 뜨고 ICCU 폭탄 터짐.",
    ),
    SlangEntry(
        term="ICCU",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="통합 충전 제어 장치 결함 고질병",
        severity_weight=5,
        default_polarity=-0.90,
        safety_impact=9.5,
        functional_impact=9.5,
        economic_impact=7.5,
        example="ICCU 또 터져서 고속도로 한복판에 차 세우고 견인 기다림.",
    ),
    SlangEntry(
        term="ICCU폭탄",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="ICCU 폭탄 붙여쓰기",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        functional_impact=9.5,
        economic_impact=8.0,
        example="전기차 ICCU폭탄 터져서 뒤차랑 박을 뻔했습니다.",
    ),
    SlangEntry(
        term="통합충전제어장치",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="ICCU 공식 명칭 관련 결함",
        severity_weight=4,
        default_polarity=-0.80,
        safety_impact=8.5,
        functional_impact=9.0,
        example="통합충전제어장치 전원 이상 경고등 뜨면서 시동 안 걸림.",
    ),
    SlangEntry(
        term="배터리 광탈",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="EV 배터리 잔량이 단시간 내 비정상적으로 급격히 소모되는 현상",
        severity_weight=4,
        default_polarity=-0.80,
        functional_impact=8.0,
        convenience_impact=8.5,
        example="영하 5도에 히터 틀고 고속도로 올리자마자 배터리 광탈하더니 반토막남.",
    ),
    SlangEntry(
        term="12V 방전",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="메인 배터리가 충전되어 있어도 12V 보조 배터리가 방전되어 차량 먹통",
        severity_weight=4,
        default_polarity=-0.85,
        functional_impact=8.5,
        convenience_impact=8.5,
        example="메인 배터리 90%인데 12V 방전돼서 도어캐치 안 튀어나옴.",
    ),
    SlangEntry(
        term="12V 방전 지옥",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="고질적 암전류로 인한 잦은 12V 배터리 방전 고통",
        severity_weight=5,
        default_polarity=-0.90,
        functional_impact=9.0,
        convenience_impact=9.0,
        example="일주일에 두 번씩 12V 방전 지옥 겪다 결국 긴급출동 불렀습니다.",
    ),
    SlangEntry(
        term="벽돌차",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="저전압 방전, BMS 에러, OTA 실패로 시동과 문 열림이 불가한 고철 상태",
        severity_weight=5,
        default_polarity=-0.95,
        functional_impact=9.8,
        convenience_impact=9.0,
        example="아침에 출근하려는데 손잡이도 안 튀어나오고 완전 벽돌차 됐다.",
    ),
    SlangEntry(
        term="벽돌",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="기동 불가 상태 비유",
        severity_weight=5,
        default_polarity=-0.90,
        functional_impact=9.5,
        convenience_impact=8.5,
        example="충전기 물렸더니 에러 뜨고 벽돌돼서 렉카 불렀다.",
    ),
    SlangEntry(
        term="옥토밸브 사망",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="혹한기 테슬라 열관리 옥토밸브 결빙 파손으로 실내 히터 완전 먹통",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.0,
        functional_impact=9.5,
        convenience_impact=9.0,
        example="옥토밸브 사망해서 히터 찬바람만 나오고 앞유리 얼어붙어 견인차 부름.",
    ),
    SlangEntry(
        term="화재",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="배터리 내부 단락 열폭주 화재",
        severity_weight=5,
        default_polarity=-1.0,
        safety_impact=10.0,
        social_impact=9.5,
        example="지하주차장에서 배터리 화재 날까 봐 항상 심장 졸임.",
    ),
    SlangEntry(
        term="불쇼",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="전기차 배터리 화재 사고를 자조/비난하는 은어",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=10.0,
        social_impact=9.0,
        example="지하주차장에서 배터리 연기 나는 순간 불쇼 시작이라 답도 없다.",
    ),
    SlangEntry(
        term="열폭주",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="리튬이온 배터리 셀 연쇄 발열 파열",
        severity_weight=5,
        default_polarity=-1.0,
        safety_impact=10.0,
        social_impact=9.5,
        example="하부 긁힌 뒤로 배터리 열폭주 날까 봐 센터에 바로 입고함.",
    ),
    SlangEntry(
        term="발열 쓰로틀링",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="고속 충전 또는 연속 주행 시 모터/배터리 과열로 속도 강제 제한",
        severity_weight=4,
        default_polarity=-0.80,
        functional_impact=8.0,
        convenience_impact=7.5,
        example="초급속 물렸는데 5분 만에 발열 쓰로틀링 걸려서 30kW로 굼벵이 기어감.",
    ),
    SlangEntry(
        term="굼벵이 충전",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="배터리 온도 관리 실패 또는 펌웨어 꼼수로 충전 속도가 극단적으로 느림",
        severity_weight=3,
        default_polarity=-0.70,
        functional_impact=6.5,
        convenience_impact=8.5,
        example="겨울만 되면 350kW 이피트 물려도 굼벵이 충전돼서 1시간 서있음.",
    ),
    SlangEntry(
        term="겨울철 주행거리 반토막",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="영하 날씨에서 LFP/NCM 배터리 화학 반응 저하로 주행거리 급감",
        severity_weight=4,
        default_polarity=-0.85,
        functional_impact=8.0,
        convenience_impact=8.5,
        example="공인 450km라더니 영하 10도에 고속도로 올리니 220km 반토막 실화냐.",
    ),
    SlangEntry(
        term="뱀파이어 드레인",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="주차 대기 중 센트리/통신 모듈로 인해 하루 5~10%씩 배터리 누설 방전",
        severity_weight=3,
        default_polarity=-0.70,
        functional_impact=6.0,
        convenience_impact=8.0,
        example="공항에 닷새 세워놨더니 뱀파이어 드레인으로 30% 날아가서 충전기 겨우 감.",
    ),
    SlangEntry(
        term="충전건 고착",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="충전 완료 후 솔레노이드 락이 해제되지 않아 충전건이 안 뽑힘",
        severity_weight=4,
        default_polarity=-0.85,
        functional_impact=8.0,
        convenience_impact=8.5,
        example="비 오는 날 충전건 고착돼서 손으로 당기다 안 빠져서 한 시간 갇힘.",
    ),
    SlangEntry(
        term="충전속도 저하",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="급속 충전 스펙에 미달하는 저속 충전 현상",
        severity_weight=3,
        default_polarity=-0.65,
        functional_impact=6.5,
        convenience_impact=7.5,
        example="초급속 충전기 꽂았는데 40kW로 충전속도 저하돼서 답답함.",
    ),
    SlangEntry(
        term="BMS 에러",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="배터리 관리 시스템 센싱 오작동 및 안전 차단",
        severity_weight=4,
        default_polarity=-0.85,
        safety_impact=8.0,
        functional_impact=9.0,
        example="갑자기 계기판에 BMS 에러 뜨더니 충전 제한 걸림.",
    ),
    SlangEntry(
        term="완속 3.5kW",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="충전구 과열 화재 방지를 위해 제조사가 강제로 완속 출력을 반토막 패치함",
        severity_weight=4,
        default_polarity=-0.80,
        functional_impact=7.5,
        convenience_impact=8.5,
        example="인렛 과열된다고 잠수함 패치로 완속 3.5kW로 반토막 내버림.",
    ),
    SlangEntry(
        term="V2L",
        dimension="BATTERY_CHARGING",
        defect_category="BATTERY_CHARGING",
        meaning="차량 고전압 배터리 전력을 외부 220V로 공급하는 V2L 기능 오류/차단/방전 결함",
        severity_weight=3,
        default_polarity=-0.75,
        functional_impact=7.0,
        convenience_impact=8.0,
        example="캠핑 가서 V2L 꽂았는데 과열 경고 뜨고 전원 차단됨.",
    ),

    # -------------------------------------------------------------
    # 5. DRIVING DYNAMICS & ADAS (15 terms)
    # -------------------------------------------------------------
    SlangEntry(
        term="피쉬테일",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="빗길/눈길 회생제동 시 후륜 접지력 상실로 차체 꼬리가 좌우로 털림",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        functional_impact=8.5,
        example="비 오는 날 고가도로 이음새 밟고 회생제동 걸리니까 피쉬테일 털림.",
    ),
    SlangEntry(
        term="차체 털림",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="후륜 슬립 및 자세 제어 실패로 인한 스핀 위기",
        severity_weight=5,
        default_polarity=-0.90,
        safety_impact=9.5,
        functional_impact=8.0,
        example="빗길 코너 돌다 차체 털림 발생해서 가드레일 박을 뻔했다.",
    ),
    SlangEntry(
        term="수막현상",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="고중량 광폭 EV 타이어의 배수 불량으로 인한 빗길 활주",
        severity_weight=4,
        default_polarity=-0.85,
        safety_impact=9.0,
        example="순정 OEM 타이어 수막현상 너무 심해서 비 올 때마다 공포스러움.",
    ),
    SlangEntry(
        term="팬텀 브레이킹",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="전방에 장애물이 없는데 그림자나 육교를 오인해 시속 100km에서 급제동",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        functional_impact=8.5,
        example="고속도로 1차선 정속주행 중 유령 급제동 꽂혀서 뒤차 박을 뻔했다.",
    ),
    SlangEntry(
        term="유령 제동",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="팬텀 브레이킹의 한국어 번역 표현",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        functional_impact=8.5,
        example="터널 진입할 때마다 유령 제동 걸려서 식은땀 흘림.",
    ),
    SlangEntry(
        term="유령 급제동",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="팬텀 브레이킹 급제동 현상",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        functional_impact=8.5,
        example="맑은 날 오토파일럿 주행 중 유령 급제동 발생해서 애기 울음 터짐.",
    ),
    SlangEntry(
        term="스펀지 브레이크",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="전자식 통합 브레이크 압력 상실로 페달이 푹 꺼지고 제동 불가",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.9,
        functional_impact=9.5,
        example="브레이크 밟았는데 스펀지 누르는 것처럼 푹 들어가서 앞차 박을 뻔.",
    ),
    SlangEntry(
        term="벽돌 페달",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="전자 모터 부스트 상실로 브레이크 페달이 돌처럼 굳어 제동 불가",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.9,
        functional_impact=9.5,
        example="계기판 경고등 뜨더니 브레이크가 벽돌 페달 돼서 사이드 잡고 멈춤.",
    ),
    SlangEntry(
        term="자석 핸들",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="스티어링 휠 중앙 부분에서 자석이 붙은 것처럼 걸리며 미세 조타 불가",
        severity_weight=4,
        default_polarity=-0.80,
        safety_impact=8.5,
        functional_impact=8.0,
        convenience_impact=8.5,
        example="핸들이 특정 각도에서 자석 붙은 것처럼 턱턱 걸려서 손목 나갈 판.",
    ),
    SlangEntry(
        term="정신병 와이퍼",
        dimension="DRIVING_DYNAMICS",
        defect_category="BUILD_QUALITY",
        meaning="테슬라 비전 오토와이퍼가 비도 안 오는데 마른 유리를 미친 듯이 긁음",
        severity_weight=3,
        default_polarity=-0.75,
        functional_impact=6.0,
        convenience_impact=8.8,
        example="맑은 날 마른 와이퍼질 미친 듯이 해대서 꺼버림. 진짜 정신병 와이퍼다.",
    ),
    SlangEntry(
        term="마른 와이퍼질",
        dimension="DRIVING_DYNAMICS",
        defect_category="BUILD_QUALITY",
        meaning="마른 앞유리를 오토와이퍼가 비 오지 않는데 긁어 유리 흠집 유발",
        severity_weight=3,
        default_polarity=-0.70,
        convenience_impact=8.0,
        example="오토와이퍼 버그로 마른 와이퍼질 해서 틴팅 다 긁힘.",
    ),
    SlangEntry(
        term="블라인드 에디션",
        dimension="DRIVING_DYNAMICS",
        defect_category="BUILD_QUALITY",
        meaning="아이오닉 5 초기형 등 리어 와이퍼가 없어 폭우 시 후방 시야 0%",
        severity_weight=4,
        default_polarity=-0.80,
        safety_impact=8.0,
        convenience_impact=8.5,
        example="비 오는 날 고속도로 올리면 뒤에 아무것도 안 보이는 블라인드 에디션.",
    ),
    SlangEntry(
        term="롤백",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="경사로 재출발 시 오토홀드 해제 타이밍 오류로 뒤로 덜컹 밀림",
        severity_weight=4,
        default_polarity=-0.80,
        safety_impact=8.5,
        functional_impact=7.5,
        example="지하주차장 언덕에서 멈췄다 밟았는데 오토홀드 풀리며 롤백 심함.",
    ),
    SlangEntry(
        term="뒤로 밀림",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="경사로 오르막길 후진 현상",
        severity_weight=4,
        default_polarity=-0.80,
        safety_impact=8.5,
        functional_impact=7.5,
        example="언덕길 정차 후 악셀 밟았는데 뒤로 밀림 심해서 뒷차 닿을 뻔함.",
    ),
    SlangEntry(
        term="거북이등",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="모터 과열 또는 저SoC로 출력 제한 경고등 점등 및 40km/h 이하 주행",
        severity_weight=4,
        default_polarity=-0.85,
        safety_impact=8.5,
        functional_impact=9.0,
        example="배터리 10% 남았다고 거북이등 뜨더니 시속 50km 이상 안 나감.",
    ),
    SlangEntry(
        term="거북이 모드",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="임프홈(Limp-home) 비상 주행 모드 진입",
        severity_weight=4,
        default_polarity=-0.85,
        safety_impact=8.5,
        functional_impact=9.0,
        example="언덕 연속으로 오르다 인버터 과열로 거북이 모드 걸려서 기어감.",
    ),
    SlangEntry(
        term="오토파일럿 급발진",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="주행 보조 중 운전자 의도와 무관한 비정상 급가속",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.9,
        functional_impact=9.0,
        example="앞차 멈추는데 감속 안 하고 오토파일럿 급발진하듯 튀어나가서 식겁함.",
    ),
    SlangEntry(
        term="회생제동 멀미",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="가속 페달 조작 시 급격한 회생제동 감속으로 인한 울컥거림 및 탑승자 멀미 유발",
        severity_weight=3,
        default_polarity=-0.75,
        convenience_impact=8.5,
        functional_impact=7.0,
        example="회생제동 3단계 놓으면 울컥거려서 동승자들 전부 회생제동 멀미 호소함.",
    ),
    SlangEntry(
        term="고래소리",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="저속 주행 시 전기차 감속기/인버터 공진음 또는 가상 엔진음 이상 고주파 소음",
        severity_weight=3,
        default_polarity=-0.70,
        convenience_impact=8.0,
        functional_impact=6.5,
        example="저속 주행할 때마다 감속기에서 삐익거리는 고래소리 심하게 올라옴.",
    ),
    SlangEntry(
        term="급발진",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="전자제어 또는 모터 오류로 브레이크 미작동 및 차량 통제 불능 급가속",
        severity_weight=5,
        default_polarity=-1.0,
        safety_impact=10.0,
        functional_impact=9.5,
        example="브레이크 밟았는데 RPM 치솟으면서 급발진 의심 사고 날 뻔.",
    ),

    # -------------------------------------------------------------
    # 6. SERVICE, REPAIR & ECONOMICS (16 terms)
    # -------------------------------------------------------------
    SlangEntry(
        term="전손",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="수리비가 차량 가액을 초과하여 폐차 처리",
        severity_weight=5,
        default_polarity=-0.90,
        economic_impact=9.5,
        example="경미한 접촉사고인데 하부 배터리 케이스 닿았다고 전손 판정 뜸.",
    ),
    SlangEntry(
        term="전손폭탄",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="기가캐스팅 파손이나 경미한 배터리 하부 긁힘에 통교체 3천만원 청구",
        severity_weight=5,
        default_polarity=-0.95,
        economic_impact=9.8,
        social_impact=8.0,
        example="방지턱에 배터리 케이스 살짝 긁혔는데 통교체 견적 2,500만원 전손폭탄 맞음.",
    ),
    SlangEntry(
        term="통교체 갑질",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="모듈 수리가 가능한 부분 불량에도 배터리 팩 전체 교체 2,800만원 강요",
        severity_weight=5,
        default_polarity=-0.95,
        economic_impact=9.5,
        social_impact=8.5,
        example="셀 하나 전압 틀어졌다고 2,800만원 배터리 팩 통교체하라는 게 말이 됨?",
    ),
    SlangEntry(
        term="감가폭탄",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="출고 1~2년 만에 중고차 잔존가치가 반토막 나는 자산 손실",
        severity_weight=4,
        default_polarity=-0.85,
        economic_impact=9.0,
        social_impact=7.0,
        example="보조금 받고 6천에 샀는데 2년 만에 엔카 시세 2천 후반 찍힘. 감가폭탄 맞음.",
    ),
    SlangEntry(
        term="감가상각",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="출고 후 빠른 중고차 잔존가치 폭락 및 가격 하락으로 인한 자산 손실",
        severity_weight=4,
        default_polarity=-0.85,
        economic_impact=9.0,
        social_impact=7.0,
        example="출고 2년 만에 감가상각 50% 반토막 나서 중고차 가격 개폭망.",
    ),
    SlangEntry(
        term="공동인수",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="손해율 폭등으로 일반 자동차 보험사 가입 거부되어 공동인수 강제",
        severity_weight=4,
        default_polarity=-0.80,
        economic_impact=8.5,
        social_impact=8.0,
        example="기존 보험사에서 테슬라 갱신 거절해서 결국 400만원 내고 공동인수 들어감.",
    ),
    SlangEntry(
        term="하드웨어 인질극",
        dimension="SERVICE_ECONOMICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="이미 차에 달린 열선, 통풍 시트, 모터 출력을 월 구독료 내야 열어줌",
        severity_weight=3,
        default_polarity=-0.75,
        economic_impact=7.5,
        social_impact=8.0,
        example="내 돈 주고 산 차 시트 엉뜨 켜는데 월 2만원 내라는 하드웨어 인질극.",
    ),
    SlangEntry(
        term="입차 거부",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="아파트 및 빌딩 지하주차장에서 화재 포비아로 전기차 주차를 금지함",
        severity_weight=4,
        default_polarity=-0.85,
        social_impact=9.5,
        convenience_impact=9.0,
        example="퇴근하고 들어왔더니 입주자대표회에서 전기차 지하주차장 입차 거부함.",
    ),
    SlangEntry(
        term="지하주차장 퇴출",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="아파트 입주민 결의로 전기차를 지상으로 강제 퇴출",
        severity_weight=4,
        default_polarity=-0.85,
        social_impact=9.5,
        convenience_impact=9.0,
        example="아파트에서 전기차 지하주차장 퇴출 현수막 걸고 충전기 전원 내려버림.",
    ),
    SlangEntry(
        term="충전소 텃세",
        dimension="SERVICE_ECONOMICS",
        defect_category="BATTERY_CHARGING",
        meaning="완충 후에도 차량을 이동하지 않거나 완속 자리를 독점하는 행태",
        severity_weight=3,
        default_polarity=-0.70,
        social_impact=8.0,
        convenience_impact=8.0,
        example="충전 다 끝났는데 3박 4일째 알박기하고 텃세 부리는 놈들 극혐.",
    ),
    SlangEntry(
        term="알박기",
        dimension="SERVICE_ECONOMICS",
        defect_category="BATTERY_CHARGING",
        meaning="공용 충전기에 완충 후 방치하여 타인 충전을 방해",
        severity_weight=3,
        default_polarity=-0.70,
        social_impact=8.0,
        convenience_impact=8.0,
        example="충전기 알박기 신고했더니 보복성 문콕 당해서 경찰 불렀다.",
    ),
    SlangEntry(
        term="휠빵",
        dimension="SERVICE_ECONOMICS",
        defect_category="BUILD_QUALITY",
        meaning="돌출된 대구경 휠이 좁은 주차 램프 연석에 긁히는 손상",
        severity_weight=2,
        default_polarity=-0.60,
        economic_impact=5.0,
        convenience_impact=7.0,
        example="지하주차장 내려가다 연석에 위버터빈 휠빵 나고 멘탈 나갔다.",
    ),
    SlangEntry(
        term="TCAM 먹통",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="샤크안테나 텔레매틱스 모듈 락업으로 LTE, GPS, 스마트키 통신 두절",
        severity_weight=4,
        default_polarity=-0.85,
        functional_impact=8.5,
        convenience_impact=8.5,
        example="TCAM 먹통 돼서 스마트키 인식 안 되고 차 문도 안 열려서 긴급출동행.",
    ),
    SlangEntry(
        term="티캠",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="TCAM 통신 모듈의 한글 음차 표기",
        severity_weight=4,
        default_polarity=-0.85,
        functional_impact=8.5,
        convenience_impact=8.5,
        example="티캠 먹통 돼서 물리키로 문 열고 서비스센터까지 견인차에 실려감.",
    ),
    SlangEntry(
        term="블루핸즈 거부",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="일반 동네 블루핸즈 정비소가 고전압 EV 전문 장비 부족으로 입고 거부",
        severity_weight=3,
        default_polarity=-0.75,
        functional_impact=6.5,
        convenience_impact=8.5,
        example="경고등 떠서 동네 갔더니 블루핸즈 거부당하고 하이테크 가라네.",
    ),
    SlangEntry(
        term="블핸퇴짜",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="블루핸즈 입고 거부 은어",
        severity_weight=3,
        default_polarity=-0.75,
        convenience_impact=8.5,
        example="블핸퇴짜 맞고 직영 하이테크센터 예약 걸었더니 2개월 대기.",
    ),
    SlangEntry(
        term="하이테크 유배",
        dimension="SERVICE_ECONOMICS",
        defect_category="SERVICE_REPAIR_COST",
        meaning="부품 수급 지연으로 직영 서비스센터에 수개월간 차량이 방치되는 상황",
        severity_weight=4,
        default_polarity=-0.85,
        functional_impact=7.5,
        convenience_impact=9.0,
        economic_impact=6.5,
        example="고전압 배터리 교체 뜬 뒤로 하이테크 유배 가서 7주째 대차 타고 다님.",
    ),

    # -------------------------------------------------------------
    # 7. ADDITIONAL CRITICAL SOFTWARE & ELECTRONIC FAULTS
    # -------------------------------------------------------------
    SlangEntry(
        term="MCU 블랙아웃",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="주행 중 중앙 인포테인먼트 스크린 꺼짐 및 리셋",
        severity_weight=4,
        default_polarity=-0.85,
        safety_impact=8.0,
        functional_impact=8.5,
        example="고속도로 120km 달리는데 MCU 블랙아웃 돼서 속도도 안 보임.",
    ),
    SlangEntry(
        term="시스템 먹통",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="인포테인먼트 및 계기판 터치 먹통 현상",
        severity_weight=4,
        default_polarity=-0.80,
        functional_impact=8.0,
        convenience_impact=8.0,
        example="시속 100km로 고속도로 달리는데 내비랑 속도계 화면 동시 시스템 먹통됨.",
    ),
    SlangEntry(
        term="먹통",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="시스템 화면 꺼짐 또는 터치/조작 반응 정지 결함",
        severity_weight=4,
        default_polarity=-0.80,
        functional_impact=8.0,
        convenience_impact=8.0,
        example="주행 중 내비랑 속도계 화면 동시 먹통됨.",
    ),
    SlangEntry(
        term="OTA 벽돌",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="새벽 무선 소프트웨어 업데이트 실패로 시동 및 주행 불가",
        severity_weight=5,
        default_polarity=-0.95,
        functional_impact=9.8,
        convenience_impact=9.0,
        example="야간에 펌웨어 받더니 OTA 벽돌 돼서 다음 날 출근 말아먹음.",
    ),
    SlangEntry(
        term="어라운드뷰 왜곡",
        dimension="SOFTWARE_ELECTRONICS",
        defect_category="SOFTWARE_ELECTRONICS",
        meaning="서라운드뷰 카메라 스티칭 불량으로 진흙 반죽처럼 찌그러짐",
        severity_weight=3,
        default_polarity=-0.65,
        convenience_impact=7.5,
        example="주차하려는데 어라운드뷰 왜곡 심해서 연석 있는 줄도 몰랐다.",
    ),
    SlangEntry(
        term="황천길",
        dimension="DRIVING_DYNAMICS",
        defect_category="DRIVING_POWERTRAIN",
        meaning="주행 중 치명적 동력 상실 및 사고 위기 체감",
        severity_weight=5,
        default_polarity=-0.95,
        safety_impact=9.8,
        example="고속도로 1차로에서 갑자기 멈춰서 레알 황천길 갈 뻔했다.",
    ),
]

# Fast lookup dictionary for slang catalog by term
SLANG_CATALOG: Dict[str, SlangEntry] = {entry.term: entry for entry in RAW_SLANG_ENTRIES}


# -------------------------------------------------------------
# EMOTIONAL INTENSIFIERS, DIMINISHERS, NEGATORS & CONCESSIVES
# -------------------------------------------------------------

# Super Intensifiers (Weight multiplier x 1.8 ~ 2.0)
SUPER_INTENSIFIERS: Dict[str, float] = {
    "존나": 1.9,
    "졸라": 1.8,
    "개": 1.8,
    "씹": 2.0,
    "시발": 2.0,
    "씨발": 2.0,
    "ㅅㅂ": 2.0,
    "ㅆㅂ": 2.0,
    "개빡": 1.9,
    "개빡침": 1.9,
    "노답": 1.8,
    "미쳤": 1.8,
    "개판": 1.8,
    "폭망": 1.9,
    "쓰레기": 1.9,
    "황천길": 2.0,
    "지옥": 1.9,
    "사기꾼": 1.9,
    "극악": 1.9,
    "최악": 2.0,
    "망작": 1.8,
    "개노답": 1.9,
    "죽을 뻔": 2.0,
    "죽는 줄": 1.9,
    "식겁": 1.8,
}

# Standard Intensifiers (Weight multiplier x 1.3 ~ 1.5)
STANDARD_INTENSIFIERS: Dict[str, float] = {
    "진짜": 1.4,
    "너무": 1.4,
    "매우": 1.4,
    "엄청": 1.4,
    "상당히": 1.3,
    "극심": 1.5,
    "제대로": 1.4,
    "오지게": 1.5,
    "완전": 1.4,
    "심각": 1.5,
    "겁나": 1.4,
    "레알": 1.3,
    "정말": 1.3,
    "대놓고": 1.3,
}

# Diminishers (Weight multiplier x 0.6 ~ 0.7)
DIMINISHERS: Dict[str, float] = {
    "약간": 0.65,
    "조금": 0.65,
    "살짝": 0.65,
    "다소": 0.70,
    "그나마": 0.60,
    "그럭저럭": 0.65,
    "그닥": 0.60,
    "별로": 0.65,
    "미미": 0.60,
}

# Negators (Inverts sign x -0.85)
NEGATORS: List[str] = [
    "안",
    "못",
    "없",
    "없고",
    "없음",
    "없네",
    "없다",
    "없어",
    "아니",
    "아님",
    "아니다",
    "아닙니다",
    "전혀",
    "결코",
    "1도",
    "하나도",
    "불가",
    "없었음",
    "안남",
    "안나요",
    "안납니다",
    "안함",
]

# Concessive connectives (pre-clause x0.5, post-clause x1.5)
CONCESSIVES: List[str] = [
    "하지만",
    "그러나",
    "그런데",
    "다만",
    "반면에",
    "불구하고",
    "그렇지만",
    "한데",
]

# Sarcasm trigger positive superlative words
SARCASM_PRAISE_WORDS: List[str] = [
    "예술",
    "명작",
    "역작",
    "폼 미쳤",
    "대단하다",
    "대단하네",
    "감성",
    "갓성비",
    "훌륭",
    "완벽",
]

# Community laughing / mocking markers
LAUGHING_MARKERS: List[str] = [
    "ㅋㅋㅋ",
    "ㅎㅎㅎ",
    "ㅋㅋ",
    "ㅎㅎ",
    "ㅋ",
    "ㅎ",
    "ㄹㅇ",
]

# -------------------------------------------------------------
# STAGE 1: NOISE & EXCLUSION RULES
# -------------------------------------------------------------
NEWS_PATTERNS: List[str] = [
    r"\[속보\]",
    r"\[단독\]",
    r"\[기사\]",
    r"기자\s*$",
    r"기자\b",
    r"연합뉴스",
    r"뉴시스",
    r"뉴스1",
    r"에 따르면",
    r"밝혔다\b",
    r"전했다\b",
    r"보도했다\b",
    r"배포했다\b",
    r"리콜 발표",
    r"국토부",
    r"국토교통부",
    r"산업부",
]

STOCK_TERMS: List[str] = [
    "주가",
    "나스닥",
    "실적",
    "매수",
    "매도",
    "평단",
    "물렸다",
    "물림",
    "테슬라 주식",
    "어닝",
    "어닝쇼크",
    "어닝서프라이즈",
    "실적발표",
    "목표주가",
    "호재",
    "악재",
    "주총",
    "주주",
    "상장",
    "시총",
]

# -------------------------------------------------------------
# STAGE 2: OWNERSHIP ANCHORS & OPERATIONAL SYMPTOMS
# -------------------------------------------------------------
OWNERSHIP_ANCHORS: List[str] = [
    # First-person / vehicle ownership
    "내 차",
    "내차",
    "우리 차",
    "우리차",
    "내 차도",
    "출고",
    "인도받",
    "인도",
    "계약",
    "키로수",
    "km 주행",
    "km 탔",
    "km 달",
    "차주",
    "오너",
    "타는데",
    "몰고",
    "타고 다닌",
    "출고한",
    "내차량",
    "내 차량",
    # Service / Maintenance interaction
    "블루핸즈",
    "오토큐",
    "섭센",
    "서비스센터",
    "하이테크",
    "하이테크센터",
    "입고",
    "정비소",
    "견인차",
    "어부바",
    "어부바차",
    "렉카",
    "수리 견적",
    "견적",
    "보증수리",
    "사업소",
    # Situational / Driving contexts
    "고속도로에서",
    "고속도로",
    "퇴근길에",
    "출근길에",
    "지하주차장에서",
    "지하주차장",
    "충전기 꽂",
    "충전 중에",
    "충전하는데",
    "방지턱 넘을 때",
    "방지턱",
    "비 오는 날",
    "비올 때",
    "빗길에",
    "언덕길에서",
    "경사로",
    "주행 중",
    "주행하는데",
    "신호대기 중",
]

SYMPTOM_PREDICATES: List[str] = [
    # Acoustic / sensory
    "소리 남",
    "소리 나",
    "소리 났",
    "찌걱",
    "덜컹",
    "귀신 소리",
    "냄새",
    "물 새",
    "물 샜",
    "물 차",
    "풍절음",
    "취사소리",
    "밥솥",
    # Functional interruption
    "시동 꺼짐",
    "시동 안",
    "멈춤",
    "멈춰",
    "먹통",
    "안 켜짐",
    "안 열림",
    "안 빠짐",
    "밀림",
    "털림",
    "다운그레이드",
    "동력 상실",
    "꺼짐",
    "안 됨",
    "안 됨",
    "먹통됨",
    "터짐",
    "터졌",
    "터져",
    "안 밟힘",
    "먹통",
    "꺼져",
    "안 나감",
    # Warning / Instrument
    "경고등",
    "점검 메시지",
    "거북이등",
    "거북이",
    "벽돌",
    "에러 코드",
    "고장코드",
    "전원공급장치 점검",
    "전원공급장치",
    # Economic / Depreciation
    "감가",
    "손해",
    "반토막",
    "시세 폭락",
    "가격 폭락",
]


def find_matching_slang(text: str) -> List[SlangEntry]:
    """Identify all slang entries present in the given text.

    Sorts by term length descending to match composite idioms first.
    """
    matches: List[SlangEntry] = []
    # Sort terms by length descending to match longer terms first (e.g. 'ICCU 폭탄' before 'ICCU')
    sorted_entries = sorted(RAW_SLANG_ENTRIES, key=lambda x: len(x.term), reverse=True)
    for entry in sorted_entries:
        if entry.term in text:
            # Avoid duplicate matching of sub-terms if already represented
            matches.append(entry)
    return matches
